# Generated by Django 5.2.11 on 2026-02-09 11:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForexPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('base_currency', models.CharField(db_index=True, max_length=3)),
                ('quote_currency', models.CharField(db_index=True, max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forex_pair',
                'indexes': [models.Index(fields=['base_currency', 'quote_currency'], name='forex_pair_base_cu_a948ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForexCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day')], max_length=3)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('high', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('low', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('close', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='market.forexpair')),
            ],
            options={
                'db_table': 'forex_candle',
                'indexes': [models.Index(fields=['pair', 'timeframe', '-timestamp'], name='forex_candl_pair_id_04a6e9_idx'), models.Index(fields=['-timestamp'], name='forex_candl_timesta_87eec9_idx')],
                'unique_together': {('pair', 'timeframe', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='ForexPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('bid', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('ask', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateTimeField(auto_now=True, db_index=True)),
                ('pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshot', to='market.forexpair')),
            ],
            options={
                'db_table': 'forex_price_snapshot',
                'indexes': [models.Index(fields=['-timestamp'], name='forex_price_timesta_bb2245_idx')],
            },
        ),
    ]
