# Generated by Django 5.2.11 on 2026-02-14 06:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('bid', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('ask', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='market.forexpair')),
            ],
            options={
                'db_table': 'forex_price_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['pair', '-timestamp'], name='forex_price_pair_id_237969_idx'), models.Index(fields=['-timestamp'], name='forex_price_timesta_75c8ea_idx')],
            },
        ),
    ]
